# Generated by Django 6.0.6 on 2026-07-06 03:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviations', '0001_initial'),
        ('sops', '0002_sopdocument_created_at_sopdocument_doc_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deviationlog',
            name='discovered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deviationlog',
            name='immediate_action_taken',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deviationlog',
            name='related_sop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sops.sopdocument'),
        ),
        migrations.AddField(
            model_name='deviationlog',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deviationlog',
            name='status',
            field=models.CharField(choices=[('investigation', 'Under Investigation'), ('pending_qa', 'Pending QA Review'), ('resolved', 'Resolved')], default='investigation', max_length=50),
        ),
    ]
