# Generated by Django 6.0.6 on 2026-07-06 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0001_initial'),
        ('deviations', '0002_deviationlog_created_at_deviationlog_discovered_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capaaction',
            name='is_active',
        ),
        migrations.AddField(
            model_name='capaaction',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capaaction',
            name='is_effective',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capaaction',
            name='preventive_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capaaction',
            name='related_deviation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deviations.deviationlog'),
        ),
        migrations.AddField(
            model_name='capaaction',
            name='root_cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capaaction',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('effectiveness_check', 'Under Effectiveness Review'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
