# Generated by Django 6.0.6 on 2026-07-06 03:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sopdocument',
            name='doc_number',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sopdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sopdocument',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
