# Generated by Django 6.0.6 on 2026-07-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sops', '0002_sopdocument_created_at_sopdocument_doc_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopdocument',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Approvals & Signatures'),
        ),
        migrations.AddField(
            model_name='sopdocument',
            name='author_department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Author/Department'),
        ),
        migrations.AddField(
            model_name='sopdocument',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='Effective Date'),
        ),
        migrations.AddField(
            model_name='sopdocument',
            name='procedure_steps',
            field=models.TextField(blank=True, null=True, verbose_name='Procedure Steps'),
        ),
        migrations.AddField(
            model_name='sopdocument',
            name='purpose_scope',
            field=models.TextField(blank=True, null=True, verbose_name='Purpose & Scope'),
        ),
        migrations.AddField(
            model_name='sopdocument',
            name='roles_responsibilities',
            field=models.TextField(blank=True, null=True, verbose_name='Roles & Responsibilities'),
        ),
        migrations.AddField(
            model_name='sopdocument',
            name='safety_compliance',
            field=models.TextField(blank=True, null=True, verbose_name='Safety & Compliance'),
        ),
        migrations.AddField(
            model_name='sopdocument',
            name='tools_equipment',
            field=models.TextField(blank=True, null=True, verbose_name='Required Tools & Equipment'),
        ),
        migrations.AddField(
            model_name='sopdocument',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sopdocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('effective', 'Effective'), ('archived', 'Archived')], default='draft', max_length=50),
        ),
    ]
