# Generated by Django 6.0.6 on 2026-07-06 03:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlleddocuments',
            name='version',
        ),
        migrations.AddField(
            model_name='controlleddocuments',
            name='document_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlleddocuments',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlleddocuments',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controlleddocuments',
            name='filename',
            field=models.CharField(max_length=100),
        ),
    ]
