# Generated by Django 6.0.6 on 2026-07-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_controlleddocuments_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlledDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('category', models.CharField(default='General Documentation', max_length=100)),
                ('document_url', models.URLField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ControlledDocuments',
        ),
    ]
