# Generated by Django 6.0.6 on 2026-07-06 03:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sops', '0002_sopdocument_created_at_sopdocument_doc_number_and_more'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='related_sop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sops.sopdocument'),
        ),
    ]
