# Generated by Django 6.0.6 on 2026-07-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingrecord_completed_at_trainingrecord_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrecord',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='overdue', max_length=50),
        ),
    ]
